### ISSUE TITLE
Peer dependencies warnings with JSS 8

### ISSUE THREAD

**Issue by randysingh** [cssinjs/normalize-jss#7]
I installed the latest version of normalize-jss with JSS 8 but it seems that there are a few dependencies that need updating:

warning "normalize-jss@3.1.0" has incorrect peer dependency "jss@^6.1.0".
warning "normalize-jss@3.1.0" has incorrect peer dependency "jss-camel-case@^3.0.0".
warning "normalize-jss@3.1.0" has incorrect peer dependency "jss-global@^0.4.0".
warning "normalize-jss@3.1.0" has incorrect peer dependency "jss-vendor-prefixer@^4.0.0".

**Comment by kof** [comment]
published version 4
